code/common/models/LogSystem.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "log_system".
 *
 * @property int $id
 * @property int $user_id
 * @property int $status
 * @property int $created_at
 */
class LogSystem extends \yii\db\ActiveRecord
{
    const TT_TAOTAIKHOAN            = 0;
    const TT_KHOATAIKHOAN           = 1;

    /**
     * @return array trang thai list
     */


    public static function TT_ARRAY()
    {
        return [
            self::TT_TAOTAIKHOAN => Yii::t('backend', 'Tạo tài khoản'),
            self::TT_KHOATAIKHOAN => Yii::t('backend', 'Khóa tài khoản'),
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'log_system';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'status', 'created_at'], 'required'],
            [['user_id', 'status', 'created_at'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'user_id' => Yii::t('common', 'User ID'),
            'status' => Yii::t('common', 'Status'),
            'created_at' => Yii::t('common', 'Created At'),
        ];
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

code/backend/controllers/LogSystemController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\LogSystem;
use common\models\query\LogSystemQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LogSystemController implements the CRUD actions for LogSystem model.
 */
class LogSystemController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all LogSystem models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = LogSystem::find()->orderBy(['id'=>SORT_DESC])->all();

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single LogSystem model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */


    /**
     * Finds the LogSystem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return LogSystem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = LogSystem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }
}

code/backend/views/log-system/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\query\LogSystemQuery */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="log-system-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

code/backend/views/log-system/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\query\LogSystemQuery */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Log Systems');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="timeline-item timeline-main">
           <h1><?= $this->title?></h1>
        </div>
        <div class="timeline timeline-right">
            <?php
                if(!empty($model)){
                    foreach ($model as $data){?>
                        <!-- START TIMELINE ITEM -->
                        <div class="timeline-item timeline-item-right">
                            <div class="timeline-item-info"><?= date(' h:i:s d-m-Y',$data->created_at)?></div>
                            <div class="timeline-item-icon"><span class="fa fa-reply"></span></div>
                            <div class="timeline-item-content">
                                <div class="timeline-heading padding-bottom-0">
                                     <a href="#"><?= $data->user->username ?></a> <?php if($data->status == \common\models\LogSystem::TT_TAOTAIKHOAN) {
                                         echo 'Đã tạo mới tài khoản';
                                     }else{
                                         echo 'Đã bị vô hiệu hóa tài khoản';
                                     }  ?></a>
                                </div>
                            </div>
                        </div>
                        <!-- END TIMELINE ITEM -->
                   <?php }
                }
            ?>
        </div>
    </div>
</div>