code/common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_INACTIVE = 9;
    const STATUS_ACTIVE = 10;

    public static function TT_ARRAY()
    {
        return [
            self::STATUS_DELETED => Yii::t('backend', 'Tạm khóa'),
            self::STATUS_INACTIVE => Yii::t('backend', 'Chưa xác thực email'),
            self::STATUS_ACTIVE => Yii::t('backend', 'Hoạt động'),
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getInfoProfile()
    {
        return $this->hasOne(InfoProfile::className(), ['id' => 'user_id']);
    }
}

code/backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\ChangePassword;
use backend\models\ChangePasswordForm;
use backend\models\SignupForm;
use common\models\AuthAssignment;
use common\models\Banner;
use common\models\CatArticles;
use common\models\InfoProfile;
use common\models\LogSystem;
use Yii;
use common\models\User;
use common\models\query\UserQuery;
use yii\rbac\Permission;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserQuery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    function actionCreate()
    {
        $model = new SignupForm();
        $AuthAssignment = new AuthAssignment();
        $connection  = Yii::$app->getDb();
        $data = $connection->createCommand("
        SELECT * FROM `auth_item` WHERE name NOT LIKE '%/%'
        ");
        $results = $data->queryAll();

//        $arrayName = array();
//        foreach ($result as $item){
//            $arrayName[] = $item["name"];
//        }
//        echo '<pre>';
//        print_r($arrayName);
//        die();
        if ($model->load(Yii::$app->request->post())) {
//            $checkBoxs = Yii::$app->request->post('checkBox');
//            echo '<pre>';
//            print_r(Yii::$app->request->post());
//            die();
            $user = new User();
            $user->username = $model->username;
            $user->email = $model->email;
            $user->status = User::STATUS_ACTIVE;
            $user->setPassword($model->password);
            $user->generateAuthKey();
            $user->generateEmailVerificationToken();
            if ($user->save()){
                // tạo acc inforProfile của tài khoản
                $modelInfoProFile = new InfoProfile();
                $modelInfoProFile->user_id = $user->id;
                $modelInfoProFile->full_name = $user->username;

                $modelLog = new LogSystem();
                $modelLog->user_id = $user->id;
                $modelLog->created_at = strtotime('now');
                $modelLog->status = LogSystem::TT_TAOTAIKHOAN;
                $modelLog->save();
                $modelInfoProFile->save();
                Yii::$app->session->setFlash('success', Yii::t('app','Thêm mới thành công.'));
                return $this->redirect('index');
            }

        }
        return $this->render('create', [
            'model' => $model,
            'results' => $results,
            'AuthAssignment' => $AuthAssignment,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */

    public function actionDoiMatKhau($id)
    {
        $user = User::findOne($id);
        $infoId = InfoProfile::find()->where(['user_id'=>$id])->one();
        $model = new ChangePasswordForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $user = User::findOne($id);
                $user->setPassword($model->newPassword);
                $user->generateAuthKey();
                if ($user->save()){
                    Yii::$app->session->setFlash('success', Yii::t('app','Thay đổi mât khẩu thành công.'));
                    return $this->redirect(['/info-profile/update','id'=>$infoId->id]);
                }
            }
        }

        return $this->render('change-password', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($id)
    {
        $user = User::findOne($id);
        $user->setPassword('123456');
        $user->generateAuthKey();
        if ($user->save()){
            // reset xong sẽ gửi mật khẩu qua email cho ng dùng
            $send = Yii::$app->mailer->compose(['html' => '@common/mail/mail-password'],['id' => $id])
                ->setFrom('auto@hellomedia.vn')
                ->setTo($user->email)
                ->setSubject('Thư xác nhận thay đổi mật khẩu - Baohiemso.net')
                ->send();
            //Chưa xử lý
            Yii::$app->session->setFlash('success', Yii::t('app','Reset mật khẩu thành công.'));
            return $this->redirect(['user/index']);
        }
    }
     public function actionKhoaTaiKhoan($id)
    {
        $user = User::findOne($id);
        $user->status = User::STATUS_DELETED;
        if ($user->save()){
            $send = Yii::$app->mailer->compose(['html' => '@common/mail/mail-khoa-tai-khoan'],['id' => $id])
                ->setFrom('auto@hellomedia.vn')
                ->setTo($user->email)
                ->setSubject('Thông báo xác thực tạm khóa tài khoản - Baohiemso.net')
                ->send();
            Yii::$app->session->setFlash('success', Yii::t('app','Tạm khóa tài khoản thành công.'));
            return $this->redirect(['user/index']);
        }
    }   

    public function actionDelete($id){
        $model = User::findOne($id);
        $model->delete();
        Yii::$app->session->setFlash('success', Yii::t('app','Xóa tài khoản thành công.'));
        return $this->redirect(['index']);
    }
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

code/backend/views/user/_form.php
<?php

use kartik\widgets\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php $form = \yii\widgets\ActiveForm::begin(); ?>
<?php echo $form->errorSummary($model); ?>
    <div class="row">
        <div class="col-md-12">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>
        </div>
    </div>
    </div>
    <div class="panel-footer">
        <?= Html::submitButton('Đăng ký', ['class' => 'btn btn-info', 'name' => 'login-button']) ?>

        <?= Html::a('Quay lại',['index'],['class'=>'btn btn-default pull-right'])?>
    </div>
<?php ActiveForm::end(); ?>

code/backend/views/user/_form_password.php
<?php

use kartik\widgets\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<div class="user-update">
    <div class="panel panel-default">
        <div class="panel-body">
            <?php $form = ActiveForm::begin();?>

            <?= $form->field($model, 'oldPassword')->passwordInput() ?>

            <?= $form->field($model, 'newPassword')->passwordInput() ?>

            <?= $form->field($model, 'retypePassword')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Thay đổi'), ['class' => 'btn btn-success']) ?>
                <?= Html::a(Yii::t('app', 'Quay lại'),'index', ['class' => 'btn btn-default pull-right']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

code/backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\query\UserQuery */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'verification_token') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

code/backend/views/user/change-password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
?>
<div class="info-profile-update">
    <?= $this->render('/user/_form_password', [
        'model' => $model,
    ]) ?>

</div>

code/backend/views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = Yii::t('app', 'Tạo tài khoản');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <?= $this->render('_form', [
        'model' => $model,
        'results' => $results,
        'AuthAssignment' => $AuthAssignment,
    ]) ?>

</div>

code/backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\query\UserQuery */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Tài khoản hệ thống');
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    button.btn-submit {
    width: 100%;
    border: none;
    text-align: left;
    padding-left: 12px;
    padding-top: 7px;
    padding-bottom: 7px;
    background: no-repeat;
}
</style>
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?= Html::a('Tạo tài khoản', ['create'], ['class' => 'btn btn-primary']) ?>
            <br>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    
                    'username',
//                    'auth_key',
//                    'password_hash',
//                    'password_reset_token',
                    'email:email',
                    [
                        'attribute'=>'status',
                        'format'=>'html',
                        'filter' => \common\models\User::TT_ARRAY(),
                        'value'=>function($data){
                            return \common\models\User::TT_ARRAY()[(int)$data->status];
                        }
                    ],
                    [
                        'header' => 'Chức năng',
                        'headerOptions' => ['style' => 'width:80px;'],
                        'format' => 'raw',
                        'contentOptions'=> ['style' => 'vertical-align: middle;font-size:17px; text-align:center'],
                        
                        'value' => function ($data) {
                            $strButton = '<div class="btn-group">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle" aria-expanded="true"><span class="glyphicon glyphicon-cog"></span></a>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                    <li>
                                        <a href="'.\yii\helpers\Url::to(['rbac/assignment/view','id'=>$data->id]).'" >Phân quyền</a>
                                    </li>
                                    <li>
                                        <a href="'.\yii\helpers\Url::to(['user/reset-password','id'=>$data->id]).'"  onclick="return confirm(\'Bạn có chắc chắn muốn reset mật khẩu hay không?\');">Reset password
                                        </a>
                                    </li>
                                    <li>
                                        <a href="'.\yii\helpers\Url::to(['khoa-tai-khoan','id'=>$data->id]).'" onclick="return confirm(\'Bạn có chắc chắn muốn khóa tài khoản này hay không?\');">Khóa tài khoản
                                        </a>
                                    </li>
                                    <form action="'.\yii\helpers\Url::to(['delete','id'=>$data->id]).'" method="post" onclick="return confirm(\'Bạn có chắc chắn muốn xóa tài khoản này hay không?\');">
                                                <button type="submit" class="btn-submit"> Xóa</button>
                                    </form>     
                                </ul>
                            </div>
                            ';
                            return 	$strButton;
                        },
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <br>
                <?= Html::a('Quay lại',['/site/index'],['class'=>'btn btn-default pull-right'])?>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>

code/backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = Yii::t('app', 'Update User: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

code/backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
            'verification_token',
        ],
    ]) ?>

</div>