code/common/models/Articles.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "articles".
 *
 * @property int $id
 * @property int $cat_articles_id
 * @property string $title
 * @property string $description
 * @property string $content
 * @property string $tags
 * @property int $created_at
 * @property int $status
 * @property int $author
 * @property int $views
 * @property string $avatar
 * @property int $is_del
 * @property int $is_hot_new
 *  @property int $type
 */
class Articles extends \yii\db\ActiveRecord
{
    const TT_MOI            = 0;
    const TT_CHOKIEMDUYET     = 1;
    const TT_DUOCDUYET      = 2;
    const TT_KIEMTRALAI     = 3;

    const T_TINTUC              = 3;
    const T_DULICH              = 1;
    const T_DACSANQUEHUONG      = 2;

    const IS_ACTIVE         = 0;
    const IS_DEL            = 1;

    public static function T_ARRAY()
    {
        return [
            self::T_TINTUC => Yii::t('backend', 'Trang tin tức'),
            self::T_DULICH => Yii::t('backend', 'Trang du lịch'),
            self::T_DACSANQUEHUONG => Yii::t('backend', 'Đặc sản quê hương'),
        ];
    }
    public static function T_COLOR_ARRAY()
    {
        return [
            self::T_TINTUC => 'label label-default',
            self::T_DULICH => 'label label-success',
            self::T_DACSANQUEHUONG => 'label label-eurro',
        ];
    }

    /**
     * @return array trang thai list
     */


    public static function TT_ARRAY()
    {
        return [
            self::TT_MOI => Yii::t('backend', 'Mới tạo'),
            self::TT_DUOCDUYET => Yii::t('backend', 'Được duyệt'),
            self::TT_KIEMTRALAI => Yii::t('backend', 'Kiểm tra lại'),
            self::TT_CHOKIEMDUYET => Yii::t('backend', 'Kiểm duyệt'),
        ];
    }
    public static function TT_COLOR_ARRAY()
    {
        return [
            self::TT_MOI => 'label label-default',
            self::TT_DUOCDUYET => 'label label-success',
            self::TT_KIEMTRALAI => 'label label-eurro',
            self::TT_CHOKIEMDUYET => 'label label-warning',
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'articles';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'description', 'content', 'tags', 'created_at', 'status', 'author', 'avatar', 'is_del'], 'required'],
            [['cat_articles_id', 'created_at', 'status', 'author', 'views', 'is_del','is_hot_new','type'], 'integer'],
            [['content', 'tags'], 'string'],
            [['avatar'], 'safe'],
            [['title', 'description', 'slug'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cat_articles_id' => 'Nhóm bài viết',
            'title' => 'Tiêu đề bài viết',
            'description' => 'Mô tả ngắn',
            'content' => 'Nội dung',
            'tags' => 'Tags',
            'created_at' => 'Thời gian tạo',
            'status' => 'Trạng thái',
            'author' => 'Tác giả',
            'views' => 'Lượt xem',
            'avatar' => 'Avatar',
            'is_del' => 'Đã xóa',
            'is_hot_new' => 'Bài viết tiêu biểu',
            'type' => 'Trang tin'
        ];
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'author']);
    }
    public function getCatArtiles()
    {
        return $this->hasOne(CatArticles::className(), ['id' => 'cat_articles_id']);
    }
}

code/backend/controllers/ArticlesController.php
<?php

namespace backend\controllers;

use common\models\Articles;
use common\models\CatArticles;
use common\models\Products;
use Yii;
use common\models\query\ArticlesQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\Pagination;
use common\models\Tags;

/**
 * ArticlesController implements the CRUD actions for Articles model.
 */
class ArticlesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new ArticlesQuery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->orderBy(['id' => SORT_DESC]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
  

    /**
     * Displays a single Articles model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($slug)
    {
        $model = Articles::find()->where(['slug' => $slug])->one();
        $tagsNames = explode(',', $model->tags);
        $modelBaiVietLienQuans = Articles::find()->where(['cat_articles_id' => 1])->andWhere(['NOT IN', 'slug', [$slug]])->limit(10)->all();
        $modelCats = CatArticles::find()->all();
        return $this->render('view', [
            'model' => $model,
            'modelBaiVietLienQuans' => $modelBaiVietLienQuans,
            'tagsNames' => $tagsNames,
            'modelCats' => $modelCats,
        ]);
    }
    public function actionDisable($id){
        $model = Articles::findOne($id);
        $model->status = Articles::TT_MOI;
        $model->save();
        $searchModel = new ArticlesQuery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['is_del' => Articles::IS_ACTIVE])->orderBy(['id' => SORT_DESC]);
        Yii::$app->session->setFlash('success', Yii::t('app', 'Ẩn bài viết thành công.'));
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionActive($id){
        $model = Articles::findOne($id);
        $model->status = Articles::TT_DUOCDUYET;
        $model->save();
        $searchModel = new ArticlesQuery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['is_del' => Articles::IS_ACTIVE])->orderBy(['id' => SORT_DESC]);
        Yii::$app->session->setFlash('success', Yii::t('app', 'Kích hoạt bài viết thành công.'));
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDel($id){
        $model = Articles::findOne($id);
        $model->is_del = Articles::IS_DEL;
        $model->save();
        $searchModel = new ArticlesQuery();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->where(['is_del' => Articles::IS_ACTIVE])->orderBy(['id' => SORT_DESC]);
        Yii::$app->session->setFlash('success', Yii::t('app', 'Xóa bài viết thành công.'));
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Articles model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Articles();
        $model->type = Articles::T_TINTUC;
        if ($model->load(Yii::$app->request->post())) {
            $model->is_del = Articles::IS_ACTIVE;
            $model->author = Yii::$app->user->identity->id;
            $model->status = Articles::TT_MOI;
            $model->created_at = strtotime("now");
            $model->views = 1;
            // convert base64 to image
            $data = $model->avatar;
            $fileName = explode('+', $data);
            $strFileName = $fileName[0];

            $position = strpos($strFileName, '.', 0);
            $strFileName = substr($strFileName, 0, $position) . strtotime("now") . '.png';

            $strEx = explode('base64,', $data);
            $imgFile = base64_decode($strEx[1]);

            file_put_contents(Yii::$app->basePath . '/web/upload/articles/' . $strFileName, $imgFile);
            $model->avatar = $strFileName;
            
            if ($model->save()) {

                $tagsNames = explode(',', $model->tags);
                if (!empty($tagsNames)) {
                    foreach ($tagsNames as $tagsNames => $values) {
                        $modelTags = new Tags();
                        $modelTags->tag_name = $values;
                        $modelTags->articles_id = $model->id;
                        $modelTags->save();
                    }
                }
                $modelCat = CatArticles::find()->where(['id' => $model->cat_articles_id])->one();
                if(!empty($modelCat)){
                    if (!$model->status == CatArticles::IS_ACTIVE) {
                        $modelCat->status = CatArticles::IS_ACTIVE;
                        $modelCat->save();
                    }
                }
                Yii::$app->session->setFlash('success', Yii::t('app', 'Thêm mới thành công.'));
                return $this->redirect(['view', 'slug' => $model->slug]);
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Articles model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $str = $model->avatar;
        if ($model->load(Yii::$app->request->post())) {
            $model->updated_at = strtotime("now");
            if ($model->avatar == $str) {
                $model->avatar = $str;
            } else {
                $data = $model->avatar;
                if (!empty($model->avatar)) {
                    $fileName = explode('+', $data);
                    $strFileName = $fileName[0];

                    $position = strpos($strFileName, '.', 0);
                    $strFileName = substr($strFileName, 0, $position) . strtotime("now") . '.png';

                    $strEx = explode('base64,', $data);
                    $imgFile = base64_decode($strEx[1]);

                    file_put_contents(Yii::$app->basePath . '/web/upload/articles/' . $strFileName, $imgFile);
                    $model->avatar = $strFileName;
                }
            }

            if ($model->save()) {
                Yii::$app->db->createCommand("DELETE FROM tags WHERE articles_id =" . $model->id)->query();
                $tagsNames = explode(',', $model->tags);
                if (!empty($tagsNames)) {
                    foreach ($tagsNames as $tagsNames => $values) {
                        $modelTags = new Tags();
                        $modelTags->tag_name = $values;
                        $modelTags->articles_id = $model->id;
                        $modelTags->save();
                    }
                }

                $modelCat = CatArticles::find()->where(['id' => $model->cat_articles_id])->one();
                if(!empty($modelCat)){
                    if (!$model->status == CatArticles::IS_ACTIVE) {
                        $modelCat->status = CatArticles::IS_ACTIVE;
                        $modelCat->save();
                    }
                }
                Yii::$app->session->setFlash('success', Yii::t('app', 'Cập nhật thành công.'));
                return $this->redirect(['view', 'slug' => $model->slug]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Articles model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionIsDelete($id)
    {
        $model = Articles::findOne($id);
        $model->is_del = Articles::IS_DEL;
        if ($model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Xóa thành công.'));
            return $this->redirect(['index']);
        }
    }

    public function actionListArticlesCat($catId)
    {

        $query = Articles::find()->where(['cat_articles_id' => $catId]);
        $countQuery = clone $query;
        $pages = new Pagination(['pageSize' => 5, 'totalCount' => $countQuery->count()]);
        $model = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();


        $cat = CatArticles::findOne($catId);
        $modelCats = CatArticles::find()->andWhere(['NOT IN', 'id', [$catId]])->all();
        $articlesViews = Articles::find()->where(['cat_articles_id' => $catId])->orderBy(['views' => SORT_DESC])->limit(10)->all();
        return $this->render('list-articles-cat', [
            'model' => $model,
            'pages' => $pages,
            'cat' => $cat,

code/frontend/views/articles/list-articles-cat.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
$this->title = 'Cây đa la tiến';
?>
<section class="list_articles_previews">
        <div class="container">
            <div class="row">
                <div class="col-md-8 list_articles_left">
                    <h2 class="title_cat">Tin tức</h2>
                    <div class="title_list_articles">
                        <ul>
                            <?php 
                            if(!empty($cats)){
                                foreach($cats as $cat){ ?>
                                    <li>
                                        <a href="<?= Url::to(['/articles/list-articles-cat','slug'=>$cat->code])?>"><?= $cat->name ?></a>
                                    </li>
                                    </li>
                                <?php }
                            }
                            ?>
                        </ul>
                    </div>
                    <?php 
                    if(!empty( $models)){
                        foreach( $models as  $article){ ?>
                            <div class="item_articles">
                                <div class="col-sm-5 item_articles_img ">
                                    <a href="<?= Url::to(['/articles/view','slug'=>$article->slug])?>"><img src="<?= Yii::getAlias('@fakelink/upload/articles/' . $article->avatar) ?>" alt=""></a>
                                </div>
                                <div class="col-sm-7 item_articles_content">
                                    <a href="<?= Url::to(['/articles/view','slug'=>$article->slug])?>">
                                        <h3 class="title"><?= $article->title?></h3>
                                    </a>
                                    <p class="description"><?= $article->description ? $article->description : '' ?></p>
                                    <a href="<?= Url::to(['/articles/view','slug'=>$article->slug])?>" class="view_more">XEM CHI TIẾT ></a>
                                </div>
                            </div>
                        <?php }
                    }
                    ?>
                    
                    <nav class="page" aria-label="Page navigation example text-center">
                        <?=
                            LinkPager::widget([
                                'pagination' => $pages,
                            ]);
                        ?>
                    </nav>
                    <div class="bottom-border">
                        
                    </div>
                </div>
                <div class="col-md-4 list_articles_right">
                    <div class="cat"></div>
                    <div class="title_list_articles">
                        <h3 class="title">Tin nổi bật</h3>
                    </div>
                    <?php 
                    if(!empty($hotNews)){
                        foreach($hotNews as $hotNew){ ?>
                            <div class="item_articles_more_viewed_date">
                                <a href="<?= Url::to(['/articles/view','slug'=>$hotNew->slug])?>">
                                    <h3 class="title_new"><?= $hotNew->title ?></h3>
                                </a>
                                <a href="" class="cat_articles"><?= $hotNew->catArtiles->name ?></a>
                            </div>
                        <?php }
                    }
                    ?>
                </div>
            </div>
        </div>
    </section>

code/frontend/views/articles/list-articles.php
<?php
use yii\widgets\LinkPager;
use yii\helpers\Url;
?>


<div class="banner_main bk-detail-product">
    <div class="breadcrumb">
        <p>
            <a href="#">Góc chuyên gia</a>
            <i class="fal fa-chevron-right"></i>
            <a href="#">Câu chuyện</a>
        </p>
    </div>
</div>
<!-- end header -->
<div id="wrapper" class="check">

    <!-- main-content -->
    <div class="news">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="row">
                        <div class="ileft col-lg-9">
                                <?php
                                if (!empty($models)){
                                    foreach ($models as $model) {?>
                                        <div class="item row">
                                            <div class="image col-md-6">
                                                <a href="<?= \yii\helpers\Url::to(['/articles/view','slug'=>$model->slug])?>">
                                                    <?php
                                                    if(!empty($model->avatar)){?>
                                                        <img src="<?= Yii::getAlias('@fakelink/articles/'.$model->avatar)?>" class="avatar  img-thumbnail" >
                                                    <?php }else{?>
                                                        <img src="https://via.placeholder.com/300x200" id="avatarPro"  class="avatar  img-thumbnail" alt="avatar">
                                                    <?php }
                                                    ?>
                                                </a>
                                            </div>
                                            <div class="info col-md-6">
                                                <a href="<?= \yii\helpers\Url::to(['/articles/view','slug'=>$model->slug])?>" class="title"><?= $model->title ?></a>
                                                <p><?= $model->desc ? $model->desc : ''?> …</p>
                                                <a href="<?= \yii\helpers\Url::to(['/articles/view','slug'=>$model->slug])?>" class="more">Chi tiết <i class="far fa-chevron-right"></i></a>
                                            </div>
                                        </div>
                                    <?php }
                                }
                                ?>

                            <nav class="page" aria-label="Page navigation example text-center">
                                <?=
                                    LinkPager::widget([
                                        'pagination' => $pages,
                                    ]);
                                ?>
                            </nav>
                        </div>
                        <div class="iright col-lg-3">
                            <h3>Góc chuyên gia</h3>
                            <ul>
                                <?php
                                if (!empty($catArticles)){
                                    foreach ($catArticles as $catArticle){?>
                                        <li><a href="<?= Url::to(['/articles/list-articles-cat','code'=>$catArticle->code])?>"><?= $catArticle->name ?></a></li>
                                    <?php }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- partner -->
    <?= $this->render('/layouts/parter') ?>
    <!-- end  parter-->

</div>

code/frontend/views/articles/search.php
<?php
use yii\widgets\LinkPager;
use yii\helpers\Url;
use common\models\CatArticles;
?>
<style>
.page-title {
    font-size: 18px;
    font-weight: 600;
    color: #00599f;
    text-transform: uppercase;
}
h2.title_cat{
    font-size: 18px !important;
}
</style>
    
    <!-- main-content -->
    <section class="list_articles_previews">
        <div class="container">
            <div class="row">
                <div class="col-md-12 list_articles_left">
                    <h2 class="title_cat text-center">Từ khóa tìm kiếm : <?= $key?></h2>
                    <div class="title_list_articles">
                        <ul>
                            <?php 
                            if(!empty($cats)){
                                foreach($cats as $cat){ ?>
                                    <li>
                                        <a href="<?= Url::to(['/articles/list-articles-cat','slug'=>$cat->code])?>"><?= $cat->name ?></a>
                                    </li>
                                <?php }
                            }
                            ?>
                        </ul>
                    </div>
                    <?php 
                    if(!empty($models)){
                        foreach($models as $model){ ?>
                            <div class="item_articles">
                                <div class="col-sm-5 item_articles_img ">
                                    <a href=""><img src="/theme/images/du-lich/img_item_articles.png" alt=""></a>
                                </div>
                                <div class="col-sm-7 item_articles_content">
                                    <a href="">
                                        <h3 class="title"><?= $model->title?></h3>
                                    </a>
                                    <p class="description"><?= $model->description?></p>
                                    <a href="<?= Url::to(['/articles/view','slug'=>$model->slug])?>" class="view_more">XEM CHI TIẾT ></a>
                                </div>
                            </div>
                        <?php }
                    }
                    ?>
                    
                    <?=
                        LinkPager::widget([
                            'pagination' => $pages,
                        ]);
                    ?>
                    <div class="bottom-border">
                        
                    </div>
                </div>
                
            </div>
        </div>
    </section>

code/frontend/views/articles/view.php
<?php
use yii\helpers\Url;
?>
<section class="list_articles_previews">
    <div class="container">
        <div class="row">
            <div class="col-md-8 list_articles_left">
                <div class="detail-article">
                    <h3 class="title_articles">
                        <?= $articles->title ? $articles->title : '' ?>
                    </h3>
                    <hr>
                    <span class="time"><i class="fal fa-clock"></i> <?= date('H:i d/m/Y',$articles->created_at)?></i></span>
                    <br>
                    <br>
                    <p class="description">
                        <?= $articles->description ? $articles->description : '' ?>
                    </p>
                    <hr>
                    <p class="contents">
                        <?= $articles->content ? $articles->content : '' ?>          
                    </p>
                    <i class="float-right bold">
                        Nguồn: <?= ucfirst($articles->user->username) ?>
                    </i>
                    <br>
                    <div class="tags">
                        <b><img src="/theme/images/tags.png" alt="">Từ khóa: </b> 
                        <?php
                        if (!empty($tagsNames)){
                            foreach ($tagsNames as $tagsNames=> $values){?>
                            <a href="<?= Url::to(['list-articles-tags','tag'=>$values])?>" class="tags"><?= $values ?></a>
                        <?php }
                        }
                        ?>
                        
                    </div>
                </div>
                <br>
                <div class="bottom-border">
                </div>
            </div>
            <div class="col-md-4 list_articles_right">
                <div class="title_list_articles">
                    <h3 class="title">Tin nổi bật</h3>
                </div>
                <?php 
                if(!empty($tinNoiBats)){
                    foreach($tinNoiBats as $tinNoiBat){ ?>
                        <div class="item_articles_more_viewed_date">
                            <a href="">
                                <h3 class="title_new"><?=  $tinNoiBat->title ?></h3>
                            </a>
                        <a href="<?= Url::to(['list-articles-cat','code'=>$tinNoiBat->catArtiles->code])?>" class="cat_articles"><?=  $tinNoiBat->catArtiles->name ?></a>
                    </div>
                    <?php }
                }
                ?>
            </div>
        </div>
    </div>
</section>